import { describe, expect, it } from 'vitest';
import { toProviderNeutralMediaAlt, toProviderNeutralMediaLabel } from '../lib/commerce/media-presentation.js';

describe('customer media presentation', () => {
  it('preserves a reviewed provider-neutral accessible description', () => {
    expect(toProviderNeutralMediaAlt(
      'Front view of the black CARLOPHILLIPS Signature Hoodie',
      'CARLOPHILLIPS Signature Hoodie'
    )).toBe('Front view of the black CARLOPHILLIPS Signature Hoodie');
  });

  it('replaces generated provider metadata with truthful AI-assisted copy', () => {
    const alt = toProviderNeutralMediaAlt(
      'Product — Generated | Generated by Modelize',
      'CARLOPHILLIPS Signature Hoodie'
    );

    expect(alt).toBe('CARLOPHILLIPS Signature Hoodie — AI-assisted product visualisation');
    expect(alt.toLowerCase()).not.toMatch(/shopify|modelize|apliiq|generated by/);
  });

  it('removes non-generative provider names without changing the product identity', () => {
    for (const source of ['Shopify product image', 'Apliiq product front']) {
      const alt = toProviderNeutralMediaAlt(source, 'CARLOPHILLIPS Signature Hoodie');
      expect(alt).toBe('CARLOPHILLIPS Signature Hoodie — product view');
      expect(alt.toLowerCase()).not.toMatch(/shopify|modelize|apliiq|generated by/);
    }
  });

  it('removes provider names from visible customer media labels', () => {
    expect(toProviderNeutralMediaLabel('Modelize product portrait · generated candidate · approval pending'))
      .toBe('AI-assisted product study · approval pending');
    expect(toProviderNeutralMediaLabel('Recorded Apliiq front candidate — approval pending'))
      .toBe('Recorded product view · approval pending');
    expect(toProviderNeutralMediaLabel('Front view')).toBe('Front view');
  });
});
