import { mkdirSync, writeFileSync } from 'node:fs';
import { chromium } from '/Users/edv/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';

const candidateUrl = process.env.CP_QA_BASE_URL || 'http://127.0.0.1:3109';
const productionUrl = 'https://www.carlophillips.com';
const evidenceRoot = 'test_reports/cp-v1.2.2-uat-correction-2026-08-14';
const screenshotRoot = `${evidenceRoot}/screenshots`;
const executablePath = '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
const providerPattern = /shopify|modelize|apliiq|generated by/i;
const viewports = [
  { name: 'desktop', width: 1440, height: 1000 },
  { name: 'compact', width: 584, height: 486 },
  { name: 'mobile', width: 390, height: 844 },
];
const routes = [
  { name: 'shop', path: '/shop', expectedBackground: 'rgb(2, 2, 2)' },
  { name: 'pdp', path: '/products/carlophillips-signature-hoodie', expectedBackground: 'rgb(0, 0, 0)' },
  { name: 'bag', path: '/bag', expectedBackground: 'rgb(2, 2, 2)' },
];

async function settle(page) {
  await page.waitForLoadState('domcontentloaded');
  await page.waitForLoadState('networkidle', { timeout: 15000 }).catch(() => {});
  await page.evaluate(() => document.fonts.ready);
  await page.waitForTimeout(150);
}

async function decodeMedia(page) {
  return page.evaluate(async () => {
    const originalY = window.scrollY;
    const step = Math.max(240, Math.floor(window.innerHeight * 0.75));
    for (let y = 0; y < document.documentElement.scrollHeight; y += step) {
      window.scrollTo(0, y);
      await new Promise(resolve => setTimeout(resolve, 30));
    }
    const images = [...document.images];
    await Promise.all(images.map(image => image.decode?.().catch(() => {})));
    const videos = [...document.querySelectorAll('video')];
    window.scrollTo(0, originalY);
    return {
      imageCount: images.length,
      brokenImages: images
        .filter(image => image.complete && image.naturalWidth === 0)
        .map(image => image.currentSrc || image.src || image.alt),
      videoCount: videos.length,
      brokenVideos: videos
        .filter(video => video.error)
        .map(video => video.currentSrc || video.src || 'video'),
    };
  });
}

async function inspectRoute(browser, target, viewport, route) {
  const context = await browser.newContext({
    viewport: { width: viewport.width, height: viewport.height },
    deviceScaleFactor: 1,
    reducedMotion: 'reduce',
  });
  const page = await context.newPage();
  const consoleErrors = [];
  const pageErrors = [];
  const requestFailures = [];
  page.on('console', message => {
    if (message.type() === 'error') consoleErrors.push(message.text());
  });
  page.on('pageerror', error => pageErrors.push(error.message));
  page.on('requestfailed', request => {
    const reason = request.failure()?.errorText || 'unknown';
    if (!reason.includes('ERR_ABORTED')) requestFailures.push(`${reason}: ${request.url()}`);
  });

  const response = await page.goto(`${target.url}${route.path}`, {
    waitUntil: 'domcontentloaded',
    timeout: 60000,
  });
  await settle(page);
  const media = await decodeMedia(page);
  const state = await page.evaluate(patternSource => {
    const pattern = new RegExp(patternSource, 'i');
    const commercePage = document.querySelector('.cp-commerce-page')
      || document.querySelector('main#main-content');
    const alts = [...document.images]
      .map(image => image.getAttribute('alt') || '')
      .filter(Boolean);
    return {
      title: document.title,
      meaningfulContent: document.body.innerText.trim().length > 0,
      frameworkOverlay: Boolean(document.querySelector('[data-nextjs-dialog], .vite-error-overlay, #webpack-dev-server-client-overlay')),
      horizontalOverflow: document.documentElement.scrollWidth > window.innerWidth + 1,
      backgroundSelector: commercePage?.matches('.cp-commerce-page')
        ? '.cp-commerce-page'
        : commercePage ? 'main#main-content' : null,
      backgroundColor: commercePage ? getComputedStyle(commercePage).backgroundColor : null,
      accessibleAlts: alts,
      accessibleAltLeakage: alts.filter(alt => pattern.test(alt)),
      visibleShopifyLeakage: /shopify/i.test(document.body.innerText),
    };
  }, providerPattern.source);
  await page.screenshot({
    path: `${screenshotRoot}/${target.name}/${viewport.name}-${route.name}.png`,
  });
  await context.close();

  return {
    target: target.name,
    viewport: viewport.name,
    route: route.name,
    path: route.path,
    expectedBackground: route.expectedBackground,
    status: response?.status() || 0,
    ...state,
    media,
    consoleErrors,
    pageErrors,
    requestFailures,
  };
}

async function inspectHomeOverlay(browser, viewport) {
  const context = await browser.newContext({
    viewport: { width: viewport.width, height: viewport.height },
    deviceScaleFactor: 1,
    reducedMotion: 'reduce',
    hasTouch: viewport.name === 'mobile',
  });
  const page = await context.newPage();
  const consoleErrors = [];
  const pageErrors = [];
  page.on('console', message => {
    if (message.type() === 'error') consoleErrors.push(message.text());
  });
  page.on('pageerror', error => pageErrors.push(error.message));

  const response = await page.goto(`${candidateUrl}/`, {
    waitUntil: 'domcontentloaded',
    timeout: 60000,
  });
  await settle(page);
  const trigger = page.getByRole('button', { name: /Explore media/i });
  if (await trigger.count() === 0) {
    const accessibleAlts = await page.locator('img').evaluateAll(images => images
      .map(image => image.getAttribute('alt') || '')
      .filter(Boolean));
    const frameworkOverlay = await page.locator('[data-nextjs-dialog], .vite-error-overlay, #webpack-dev-server-client-overlay').count() > 0;
    const horizontalOverflow = await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth + 1);
    await page.screenshot({ path: `${screenshotRoot}/candidate/${viewport.name}-home.png` });
    await context.close();
    return {
      viewport: viewport.name,
      status: response?.status() || 0,
      mediaAvailable: false,
      mediaCount: 0,
      decoded: [],
      accessibleAlts,
      accessibleAltLeakage: accessibleAlts.filter(alt => providerPattern.test(alt)),
      frameworkOverlay,
      horizontalOverflow,
      overlayInset: null,
      focusReturned: null,
      consoleErrors,
      pageErrors,
    };
  }
  await trigger.focus();
  await trigger.click();
  const dialog = page.locator('#product-media-overlay');
  await dialog.waitFor({ state: 'visible' });
  const slides = page.locator('.cp-media-slide');
  const mediaCount = await slides.count();
  const decoded = [];
  const accessibleAlts = [];
  for (let index = 0; index < mediaCount; index += 1) {
    const asset = slides.nth(index).locator('img, video').first();
    await asset.scrollIntoViewIfNeeded();
    decoded.push(await asset.evaluate(async element => {
      if (element instanceof HTMLImageElement) {
        await element.decode().catch(() => {});
        return element.complete && element.naturalWidth > 0;
      }
      return !element.error && element.readyState >= 1;
    }));
    if (await asset.evaluate(element => element instanceof HTMLImageElement)) {
      accessibleAlts.push(await asset.getAttribute('alt') || '');
    }
  }
  const overlayInset = await dialog.locator('.cp-media-panel').evaluate(element => {
    const rect = element.getBoundingClientRect();
    return rect.x > 0 && rect.y > 0 && rect.width < window.innerWidth && rect.height < window.innerHeight;
  });
  await page.screenshot({ path: `${screenshotRoot}/candidate/${viewport.name}-home-overlay.png` });
  await page.keyboard.press('Escape');
  await dialog.waitFor({ state: 'detached' });
  const focusReturned = await trigger.evaluate(element => document.activeElement === element);
  await context.close();

  return {
    viewport: viewport.name,
    status: response?.status() || 0,
    mediaAvailable: true,
    mediaCount,
    decoded,
    accessibleAlts,
    accessibleAltLeakage: accessibleAlts.filter(alt => providerPattern.test(alt)),
    overlayInset,
    focusReturned,
    consoleErrors,
    pageErrors,
  };
}

mkdirSync(`${screenshotRoot}/candidate`, { recursive: true });
mkdirSync(`${screenshotRoot}/production`, { recursive: true });

const browser = await chromium.launch({
  headless: true,
  executablePath,
  args: ['--disable-background-networking', '--disable-default-apps', '--no-first-run'],
});
const report = {
  schemaVersion: 'cp.v1.2.2-uat-correction-browser-qa.v1',
  date: '2026-08-14',
  method: 'headless background Chrome; local corrected build compared with live approved Production',
  candidateUrl,
  productionUrl,
  externalMutation: false,
  routeChecks: [],
  homeOverlayChecks: [],
};

try {
  for (const viewport of viewports) {
    for (const route of routes) {
      report.routeChecks.push(await inspectRoute(browser, { name: 'candidate', url: candidateUrl }, viewport, route));
      report.routeChecks.push(await inspectRoute(browser, { name: 'production', url: productionUrl }, viewport, route));
    }
    report.homeOverlayChecks.push(await inspectHomeOverlay(browser, viewport));
  }
} finally {
  await browser.close();
}

const candidateRoutes = report.routeChecks.filter(check => check.target === 'candidate');
const productionRoutes = report.routeChecks.filter(check => check.target === 'production');
const runtimeHealthy = check => check.status === 200
  && check.meaningfulContent
  && !check.frameworkOverlay
  && !check.horizontalOverflow
  && !check.visibleShopifyLeakage
  && check.media.brokenImages.length === 0
  && check.media.brokenVideos.length === 0
  && check.consoleErrors.length === 0
  && check.pageErrors.length === 0
  && check.requestFailures.length === 0;
report.summary = {
  expectedCommerceBackgroundByRoute: Object.fromEntries(routes.map(route => [route.name, route.expectedBackground])),
  candidateBackgroundChecks: candidateRoutes.map(check => check.backgroundColor),
  productionBackgroundChecks: productionRoutes.map(check => check.backgroundColor),
  candidateBackgroundTargetPass: candidateRoutes
    .every(check => check.backgroundColor === check.expectedBackground),
  commerceBackgroundParity: [...candidateRoutes, ...productionRoutes]
    .every(check => check.backgroundColor === check.expectedBackground),
  candidateRoutesHealthy: candidateRoutes.every(check => runtimeHealthy(check)
    && check.accessibleAltLeakage.length === 0),
  productionRoutesHealthy: productionRoutes.every(runtimeHealthy),
  candidateAccessibleAltLeakage: candidateRoutes.flatMap(check => check.accessibleAltLeakage),
  productionAccessibleAltLeakageObserved: productionRoutes.flatMap(check => check.accessibleAltLeakage),
  homeOverlayHealthy: report.homeOverlayChecks.every(check => check.status === 200
    && check.accessibleAltLeakage.length === 0
    && !check.frameworkOverlay
    && !check.horizontalOverflow
    && (!check.mediaAvailable || (check.mediaCount === 12
      && check.decoded.every(Boolean)
      && check.overlayInset
      && check.focusReturned))
    && check.consoleErrors.length === 0
    && check.pageErrors.length === 0),
  screenshots: viewports.length * routes.length * 2 + viewports.length,
};

writeFileSync(`${evidenceRoot}/browser-verification.json`, `${JSON.stringify(report, null, 2)}\n`);
console.log(JSON.stringify(report.summary, null, 2));
